'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace R2PrimaryWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="R2PrimaryWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class R2PrimaryWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private WebMethodLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodPaymentRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodVerificationRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.R2Core.My.MySettings.Default.R2Core_R2PrimaryWS_R2PrimaryWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event WebMethodLoginCompleted As WebMethodLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationProviderBillOfLadingControlReportCompleted As WebMethodReportingInformationProviderBillOfLadingControlReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompleted As WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodPaymentRequestCompleted As WebMethodPaymentRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodVerificationRequestCompleted As WebMethodVerificationRequestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodLogin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodLogin(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String) As Long
            Dim results() As Object = Me.Invoke("WebMethodLogin", New Object() {YourUserShenaseh, YourUserPassword})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodLoginAsync(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String)
            Me.WebMethodLoginAsync(YourUserShenaseh, YourUserPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodLoginAsync(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String, ByVal userState As Object)
            If (Me.WebMethodLoginOperationCompleted Is Nothing) Then
                Me.WebMethodLoginOperationCompleted = AddressOf Me.OnWebMethodLoginOperationCompleted
            End If
            Me.InvokeAsync("WebMethodLogin", New Object() {YourUserShenaseh, YourUserPassword}, Me.WebMethodLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodLoginCompleted(Me, New WebMethodLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationProviderBillOfLadingControlReport"& _ 
            "", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationProviderBillOfLadingControlReport(ByVal YourBLCId As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationProviderBillOfLadingControlReport", New Object() {YourBLCId, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlReportAsync(ByVal YourBLCId As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationProviderBillOfLadingControlReportAsync(YourBLCId, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlReportAsync(ByVal YourBLCId As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationProviderBillOfLadingControlReport", New Object() {YourBLCId, YourExchangeKey}, Me.WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationProviderBillOfLadingControlReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationProviderBillOfLadingControlReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationProviderBillOfLadingControlInfrac"& _ 
            "tionsReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReport(ByVal YourBLCIId As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationProviderBillOfLadingControlInfractionsReport", New Object() {YourBLCIId, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportAsync(ByVal YourBLCIId As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportAsync(YourBLCIId, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportAsync(ByVal YourBLCIId As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationProviderBillOfLadingControlInfractionsReport", New Object() {YourBLCIId, YourExchangeKey}, Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodPaymentRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodPaymentRequest(ByVal YourMCSSId As Long, ByVal YourAmount As Long, ByVal YourSoftwareUserId As Long, ByVal YourExchangeKey As Long) As Long
            Dim results() As Object = Me.Invoke("WebMethodPaymentRequest", New Object() {YourMCSSId, YourAmount, YourSoftwareUserId, YourExchangeKey})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodPaymentRequestAsync(ByVal YourMCSSId As Long, ByVal YourAmount As Long, ByVal YourSoftwareUserId As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodPaymentRequestAsync(YourMCSSId, YourAmount, YourSoftwareUserId, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodPaymentRequestAsync(ByVal YourMCSSId As Long, ByVal YourAmount As Long, ByVal YourSoftwareUserId As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodPaymentRequestOperationCompleted Is Nothing) Then
                Me.WebMethodPaymentRequestOperationCompleted = AddressOf Me.OnWebMethodPaymentRequestOperationCompleted
            End If
            Me.InvokeAsync("WebMethodPaymentRequest", New Object() {YourMCSSId, YourAmount, YourSoftwareUserId, YourExchangeKey}, Me.WebMethodPaymentRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodPaymentRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodPaymentRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodPaymentRequestCompleted(Me, New WebMethodPaymentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodVerificationRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodVerificationRequest(ByVal YourMCSSId As Long, ByVal YourAuthority As String, ByVal YourExchangeKey As Long) As Long
            Dim results() As Object = Me.Invoke("WebMethodVerificationRequest", New Object() {YourMCSSId, YourAuthority, YourExchangeKey})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodVerificationRequestAsync(ByVal YourMCSSId As Long, ByVal YourAuthority As String, ByVal YourExchangeKey As Long)
            Me.WebMethodVerificationRequestAsync(YourMCSSId, YourAuthority, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodVerificationRequestAsync(ByVal YourMCSSId As Long, ByVal YourAuthority As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodVerificationRequestOperationCompleted Is Nothing) Then
                Me.WebMethodVerificationRequestOperationCompleted = AddressOf Me.OnWebMethodVerificationRequestOperationCompleted
            End If
            Me.InvokeAsync("WebMethodVerificationRequest", New Object() {YourMCSSId, YourAuthority, YourExchangeKey}, Me.WebMethodVerificationRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodVerificationRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodVerificationRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodVerificationRequestCompleted(Me, New WebMethodVerificationRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodLoginCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationProviderBillOfLadingControlReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodPaymentRequestCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodPaymentRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodPaymentRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodVerificationRequestCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodVerificationRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodVerificationRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
End Namespace
