'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace R2PrimaryWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="R2PrimaryWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class R2PrimaryWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private WebMethodLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerUsersChargeReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerSoldRFIDCardsReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerPresentCarsInParkingReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerBlackListFinancialReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerCarEntranceReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerTerraficCardsIdentityReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerBlackListReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodGetCurrentDateTimeMilladiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodRegisteringHandyBillsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodGetTotalRegisteredHandyBillsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodDeleteRegisteredHandyBillsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationPrividerPersonnelEnterExitReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodExistCarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodPaymentRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodVerificationRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.R2Core.My.MySettings.Default.R2Core_R2PrimaryWS_R2PrimaryWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event WebMethodLoginCompleted As WebMethodLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportCompleted As WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerUsersChargeReportCompleted As WebMethodReportingInformationPrividerUsersChargeReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerSoldRFIDCardsReportCompleted As WebMethodReportingInformationPrividerSoldRFIDCardsReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportCompleted As WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerPresentCarsInParkingReportCompleted As WebMethodReportingInformationPrividerPresentCarsInParkingReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerBlackListFinancialReportCompleted As WebMethodReportingInformationPrividerBlackListFinancialReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerCarEntranceReportCompleted As WebMethodReportingInformationPrividerCarEntranceReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerTerraficCardsIdentityReportCompleted As WebMethodReportingInformationPrividerTerraficCardsIdentityReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerBlackListReportCompleted As WebMethodReportingInformationPrividerBlackListReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodGetCurrentDateTimeMilladiCompleted As WebMethodGetCurrentDateTimeMilladiCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodRegisteringHandyBillsCompleted As WebMethodRegisteringHandyBillsCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodGetTotalRegisteredHandyBillsCompleted As WebMethodGetTotalRegisteredHandyBillsCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodDeleteRegisteredHandyBillsCompleted As WebMethodDeleteRegisteredHandyBillsCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationPrividerPersonnelEnterExitReportCompleted As WebMethodReportingInformationPrividerPersonnelEnterExitReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodExistCarCompleted As WebMethodExistCarCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationProviderBillOfLadingControlReportCompleted As WebMethodReportingInformationProviderBillOfLadingControlReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompleted As WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodPaymentRequestCompleted As WebMethodPaymentRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodVerificationRequestCompleted As WebMethodVerificationRequestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodLogin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodLogin(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String) As Long
            Dim results() As Object = Me.Invoke("WebMethodLogin", New Object() {YourUserShenaseh, YourUserPassword})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodLoginAsync(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String)
            Me.WebMethodLoginAsync(YourUserShenaseh, YourUserPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodLoginAsync(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String, ByVal userState As Object)
            If (Me.WebMethodLoginOperationCompleted Is Nothing) Then
                Me.WebMethodLoginOperationCompleted = AddressOf Me.OnWebMethodLoginOperationCompleted
            End If
            Me.InvokeAsync("WebMethodLogin", New Object() {YourUserShenaseh, YourUserPassword}, Me.WebMethodLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodLoginCompleted(Me, New WebMethodLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerMoneyWalletsCurrentCharge"& _ 
            "Report", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourExchangeKey}, Me.WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerUsersChargeReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerUsersChargeReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerUsersChargeReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerUsersChargeReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerUsersChargeReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerUsersChargeReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerUsersChargeReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerUsersChargeReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerUsersChargeReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerUsersChargeReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey}, Me.WebMethodReportingInformationPrividerUsersChargeReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerUsersChargeReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerUsersChargeReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerUsersChargeReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerSoldRFIDCardsReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerSoldRFIDCardsReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerSoldRFIDCardsReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerSoldRFIDCardsReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerSoldRFIDCardsReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerSoldRFIDCardsReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerSoldRFIDCardsReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerSoldRFIDCardsReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerSoldRFIDCardsReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerSoldRFIDCardsReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey}, Me.WebMethodReportingInformationPrividerSoldRFIDCardsReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerSoldRFIDCardsReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerSoldRFIDCardsReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerSoldRFIDCardsReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerParkingTotalEnteranceSepa"& _ 
            "rationByTerraficCardReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCar"& _ 
                    "dReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCar"& _ 
                    "dReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey}, Me.WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerPresentCarsInParkingRepor"& _ 
            "t", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerPresentCarsInParkingReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourTerraficCardType As Short, ByVal YourViewCarImages As Boolean, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerPresentCarsInParkingReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourTerraficCardType, YourViewCarImages, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerPresentCarsInParkingReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourTerraficCardType As Short, ByVal YourViewCarImages As Boolean, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerPresentCarsInParkingReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourTerraficCardType, YourViewCarImages, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerPresentCarsInParkingReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourTerraficCardType As Short, ByVal YourViewCarImages As Boolean, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerPresentCarsInParkingReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerPresentCarsInParkingReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerPresentCarsInParkingReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerPresentCarsInParkingReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourTerraficCardType, YourViewCarImages, YourExchangeKey}, Me.WebMethodReportingInformationPrividerPresentCarsInParkingReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerPresentCarsInParkingReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerPresentCarsInParkingReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerPresentCarsInParkingReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerBlackListFinancialReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerBlackListFinancialReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerBlackListFinancialReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerBlackListFinancialReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerBlackListFinancialReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerBlackListFinancialReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerBlackListFinancialReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerBlackListFinancialReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerBlackListFinancialReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerBlackListFinancialReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey}, Me.WebMethodReportingInformationPrividerBlackListFinancialReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerBlackListFinancialReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerBlackListFinancialReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerBlackListFinancialReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerCarEntranceReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerCarEntranceReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourTerraficCard As String, ByVal YourPelak As String, ByVal YourSerial As String, ByVal YourEntranceDateTimeSupport As Short, ByVal YourViewCarImages As Boolean, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerCarEntranceReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourTerraficCard, YourPelak, YourSerial, YourEntranceDateTimeSupport, YourViewCarImages, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerCarEntranceReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourTerraficCard As String, ByVal YourPelak As String, ByVal YourSerial As String, ByVal YourEntranceDateTimeSupport As Short, ByVal YourViewCarImages As Boolean, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerCarEntranceReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourTerraficCard, YourPelak, YourSerial, YourEntranceDateTimeSupport, YourViewCarImages, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerCarEntranceReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourTerraficCard As String, ByVal YourPelak As String, ByVal YourSerial As String, ByVal YourEntranceDateTimeSupport As Short, ByVal YourViewCarImages As Boolean, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerCarEntranceReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerCarEntranceReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerCarEntranceReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerCarEntranceReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourTerraficCard, YourPelak, YourSerial, YourEntranceDateTimeSupport, YourViewCarImages, YourExchangeKey}, Me.WebMethodReportingInformationPrividerCarEntranceReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerCarEntranceReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerCarEntranceReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerCarEntranceReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerTerraficCardsIdentityRepo"& _ 
            "rt", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerTerraficCardsIdentityReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerTerraficCardsIdentityReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerTerraficCardsIdentityReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerTerraficCardsIdentityReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerTerraficCardsIdentityReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerTerraficCardsIdentityReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerTerraficCardsIdentityReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerTerraficCardsIdentityReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerTerraficCardsIdentityReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey}, Me.WebMethodReportingInformationPrividerTerraficCardsIdentityReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerTerraficCardsIdentityReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerTerraficCardsIdentityReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerTerraficCardsIdentityReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerBlackListReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerBlackListReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourBlackListType As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerBlackListReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourBlackListType, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerBlackListReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourBlackListType As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerBlackListReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourBlackListType, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerBlackListReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourBlackListType As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerBlackListReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerBlackListReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerBlackListReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerBlackListReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourBlackListType, YourExchangeKey}, Me.WebMethodReportingInformationPrividerBlackListReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerBlackListReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerBlackListReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerBlackListReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodGetCurrentDateTimeMilladi", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodGetCurrentDateTimeMilladi(ByVal YourExchangeKey As Long) As Date
            Dim results() As Object = Me.Invoke("WebMethodGetCurrentDateTimeMilladi", New Object() {YourExchangeKey})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetCurrentDateTimeMilladiAsync(ByVal YourExchangeKey As Long)
            Me.WebMethodGetCurrentDateTimeMilladiAsync(YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetCurrentDateTimeMilladiAsync(ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodGetCurrentDateTimeMilladiOperationCompleted Is Nothing) Then
                Me.WebMethodGetCurrentDateTimeMilladiOperationCompleted = AddressOf Me.OnWebMethodGetCurrentDateTimeMilladiOperationCompleted
            End If
            Me.InvokeAsync("WebMethodGetCurrentDateTimeMilladi", New Object() {YourExchangeKey}, Me.WebMethodGetCurrentDateTimeMilladiOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodGetCurrentDateTimeMilladiOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodGetCurrentDateTimeMilladiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodGetCurrentDateTimeMilladiCompleted(Me, New WebMethodGetCurrentDateTimeMilladiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodRegisteringHandyBills", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodRegisteringHandyBills(ByVal YourTeadad As Long, ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodRegisteringHandyBills", New Object() {YourTeadad, YourShamsiDate, YourTerafficCardType, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodRegisteringHandyBillsAsync(ByVal YourTeadad As Long, ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodRegisteringHandyBillsAsync(YourTeadad, YourShamsiDate, YourTerafficCardType, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodRegisteringHandyBillsAsync(ByVal YourTeadad As Long, ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodRegisteringHandyBillsOperationCompleted Is Nothing) Then
                Me.WebMethodRegisteringHandyBillsOperationCompleted = AddressOf Me.OnWebMethodRegisteringHandyBillsOperationCompleted
            End If
            Me.InvokeAsync("WebMethodRegisteringHandyBills", New Object() {YourTeadad, YourShamsiDate, YourTerafficCardType, YourExchangeKey}, Me.WebMethodRegisteringHandyBillsOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodRegisteringHandyBillsOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodRegisteringHandyBillsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodRegisteringHandyBillsCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodGetTotalRegisteredHandyBills", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodGetTotalRegisteredHandyBills(ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long) As Long
            Dim results() As Object = Me.Invoke("WebMethodGetTotalRegisteredHandyBills", New Object() {YourShamsiDate, YourTerafficCardType, YourExchangeKey})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetTotalRegisteredHandyBillsAsync(ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodGetTotalRegisteredHandyBillsAsync(YourShamsiDate, YourTerafficCardType, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetTotalRegisteredHandyBillsAsync(ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodGetTotalRegisteredHandyBillsOperationCompleted Is Nothing) Then
                Me.WebMethodGetTotalRegisteredHandyBillsOperationCompleted = AddressOf Me.OnWebMethodGetTotalRegisteredHandyBillsOperationCompleted
            End If
            Me.InvokeAsync("WebMethodGetTotalRegisteredHandyBills", New Object() {YourShamsiDate, YourTerafficCardType, YourExchangeKey}, Me.WebMethodGetTotalRegisteredHandyBillsOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodGetTotalRegisteredHandyBillsOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodGetTotalRegisteredHandyBillsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodGetTotalRegisteredHandyBillsCompleted(Me, New WebMethodGetTotalRegisteredHandyBillsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodDeleteRegisteredHandyBills", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodDeleteRegisteredHandyBills(ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodDeleteRegisteredHandyBills", New Object() {YourShamsiDate, YourTerafficCardType, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodDeleteRegisteredHandyBillsAsync(ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodDeleteRegisteredHandyBillsAsync(YourShamsiDate, YourTerafficCardType, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodDeleteRegisteredHandyBillsAsync(ByVal YourShamsiDate As String, ByVal YourTerafficCardType As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodDeleteRegisteredHandyBillsOperationCompleted Is Nothing) Then
                Me.WebMethodDeleteRegisteredHandyBillsOperationCompleted = AddressOf Me.OnWebMethodDeleteRegisteredHandyBillsOperationCompleted
            End If
            Me.InvokeAsync("WebMethodDeleteRegisteredHandyBills", New Object() {YourShamsiDate, YourTerafficCardType, YourExchangeKey}, Me.WebMethodDeleteRegisteredHandyBillsOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodDeleteRegisteredHandyBillsOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodDeleteRegisteredHandyBillsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodDeleteRegisteredHandyBillsCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationPrividerPersonnelEnterExitReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationPrividerPersonnelEnterExitReport(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationPrividerPersonnelEnterExitReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerPersonnelEnterExitReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationPrividerPersonnelEnterExitReportAsync(YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationPrividerPersonnelEnterExitReportAsync(ByVal YourDateTimeMilladi1 As Date, ByVal YourShamsiDate1 As String, ByVal YourTime1 As String, ByVal YourDateTimeMilladi2 As Date, ByVal YourShamsiDate2 As String, ByVal YourTime2 As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationPrividerPersonnelEnterExitReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationPrividerPersonnelEnterExitReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationPrividerPersonnelEnterExitReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationPrividerPersonnelEnterExitReport", New Object() {YourDateTimeMilladi1, YourShamsiDate1, YourTime1, YourDateTimeMilladi2, YourShamsiDate2, YourTime2, YourExchangeKey}, Me.WebMethodReportingInformationPrividerPersonnelEnterExitReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationPrividerPersonnelEnterExitReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationPrividerPersonnelEnterExitReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationPrividerPersonnelEnterExitReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodExistCar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodExistCar(ByVal YourPelak As String, ByVal YourSerial As String, ByVal YourExchangeKey As Long) As Boolean
            Dim results() As Object = Me.Invoke("WebMethodExistCar", New Object() {YourPelak, YourSerial, YourExchangeKey})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodExistCarAsync(ByVal YourPelak As String, ByVal YourSerial As String, ByVal YourExchangeKey As Long)
            Me.WebMethodExistCarAsync(YourPelak, YourSerial, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodExistCarAsync(ByVal YourPelak As String, ByVal YourSerial As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodExistCarOperationCompleted Is Nothing) Then
                Me.WebMethodExistCarOperationCompleted = AddressOf Me.OnWebMethodExistCarOperationCompleted
            End If
            Me.InvokeAsync("WebMethodExistCar", New Object() {YourPelak, YourSerial, YourExchangeKey}, Me.WebMethodExistCarOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodExistCarOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodExistCarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodExistCarCompleted(Me, New WebMethodExistCarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationProviderBillOfLadingControlReport"& _ 
            "", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationProviderBillOfLadingControlReport(ByVal YourBLCId As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationProviderBillOfLadingControlReport", New Object() {YourBLCId, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlReportAsync(ByVal YourBLCId As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationProviderBillOfLadingControlReportAsync(YourBLCId, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlReportAsync(ByVal YourBLCId As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationProviderBillOfLadingControlReport", New Object() {YourBLCId, YourExchangeKey}, Me.WebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationProviderBillOfLadingControlReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationProviderBillOfLadingControlReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationProviderBillOfLadingControlReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodReportingInformationProviderBillOfLadingControlInfrac"& _ 
            "tionsReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReport(ByVal YourBLCIId As Long, ByVal YourExchangeKey As Long)
            Me.Invoke("WebMethodReportingInformationProviderBillOfLadingControlInfractionsReport", New Object() {YourBLCIId, YourExchangeKey})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportAsync(ByVal YourBLCIId As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportAsync(YourBLCIId, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportAsync(ByVal YourBLCIId As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted Is Nothing) Then
                Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted = AddressOf Me.OnWebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted
            End If
            Me.InvokeAsync("WebMethodReportingInformationProviderBillOfLadingControlInfractionsReport", New Object() {YourBLCIId, YourExchangeKey}, Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodReportingInformationProviderBillOfLadingControlInfractionsReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodPaymentRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodPaymentRequest(ByVal YourMCSSId As Long, ByVal YourAmount As Long, ByVal YourSoftwareUserId As Long, ByVal YourExchangeKey As Long) As Long
            Dim results() As Object = Me.Invoke("WebMethodPaymentRequest", New Object() {YourMCSSId, YourAmount, YourSoftwareUserId, YourExchangeKey})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodPaymentRequestAsync(ByVal YourMCSSId As Long, ByVal YourAmount As Long, ByVal YourSoftwareUserId As Long, ByVal YourExchangeKey As Long)
            Me.WebMethodPaymentRequestAsync(YourMCSSId, YourAmount, YourSoftwareUserId, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodPaymentRequestAsync(ByVal YourMCSSId As Long, ByVal YourAmount As Long, ByVal YourSoftwareUserId As Long, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodPaymentRequestOperationCompleted Is Nothing) Then
                Me.WebMethodPaymentRequestOperationCompleted = AddressOf Me.OnWebMethodPaymentRequestOperationCompleted
            End If
            Me.InvokeAsync("WebMethodPaymentRequest", New Object() {YourMCSSId, YourAmount, YourSoftwareUserId, YourExchangeKey}, Me.WebMethodPaymentRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodPaymentRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodPaymentRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodPaymentRequestCompleted(Me, New WebMethodPaymentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodVerificationRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodVerificationRequest(ByVal YourMCSSId As Long, ByVal YourAuthority As String, ByVal YourExchangeKey As Long) As Long
            Dim results() As Object = Me.Invoke("WebMethodVerificationRequest", New Object() {YourMCSSId, YourAuthority, YourExchangeKey})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodVerificationRequestAsync(ByVal YourMCSSId As Long, ByVal YourAuthority As String, ByVal YourExchangeKey As Long)
            Me.WebMethodVerificationRequestAsync(YourMCSSId, YourAuthority, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodVerificationRequestAsync(ByVal YourMCSSId As Long, ByVal YourAuthority As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodVerificationRequestOperationCompleted Is Nothing) Then
                Me.WebMethodVerificationRequestOperationCompleted = AddressOf Me.OnWebMethodVerificationRequestOperationCompleted
            End If
            Me.InvokeAsync("WebMethodVerificationRequest", New Object() {YourMCSSId, YourAuthority, YourExchangeKey}, Me.WebMethodVerificationRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodVerificationRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodVerificationRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodVerificationRequestCompleted(Me, New WebMethodVerificationRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodLoginCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerMoneyWalletsCurrentChargeReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerUsersChargeReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerSoldRFIDCardsReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerParkingTotalEnteranceSeparationByTerraficCardReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerPresentCarsInParkingReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerBlackListFinancialReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerCarEntranceReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerTerraficCardsIdentityReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerBlackListReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodGetCurrentDateTimeMilladiCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodGetCurrentDateTimeMilladiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodGetCurrentDateTimeMilladiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodRegisteringHandyBillsCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodGetTotalRegisteredHandyBillsCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodGetTotalRegisteredHandyBillsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodGetTotalRegisteredHandyBillsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodDeleteRegisteredHandyBillsCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationPrividerPersonnelEnterExitReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodExistCarCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodExistCarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodExistCarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationProviderBillOfLadingControlReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodReportingInformationProviderBillOfLadingControlInfractionsReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodPaymentRequestCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodPaymentRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodPaymentRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodVerificationRequestCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodVerificationRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodVerificationRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
End Namespace
