'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace RmtoWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PKG_RMTO_WSBinding", [Namespace]:="http://xmlns.oracle.com/orawsv/TR_PUBLIC_WS/PKG_RMTO_WS")>  _
    Partial Public Class PKG_RMTO_WSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RMTO_WEB_SERVICESOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.R2CoreTransportationAndLoadNotification.My.MySettings.Default.R2CoreTransportationAndLoadNotification_RmtoWS_PKG_RMTO_WSService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RMTO_WEB_SERVICESCompleted As RMTO_WEB_SERVICESCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("RMTO_WEB_SERVICES", RequestElementName:="SVARCHAR2-RMTO_WEB_SERVICESInput", RequestNamespace:="http://xmlns.oracle.com/orawsv/TR_PUBLIC_WS/PKG_RMTO_WS", ResponseElementName:="RMTO_WEB_SERVICESOutput", ResponseNamespace:="http://xmlns.oracle.com/orawsv/TR_PUBLIC_WS/PKG_RMTO_WS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RMTO_WEB_SERVICES(<System.Xml.Serialization.XmlElementAttribute("IN_PARAM_1-VARCHAR2-IN")> ByVal IN_PARAM_1VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_10-VARCHAR2-IN")> ByVal IN_PARAM_10VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_2-VARCHAR2-IN")> ByVal IN_PARAM_2VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_3-VARCHAR2-IN")> ByVal IN_PARAM_3VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_4-VARCHAR2-IN")> ByVal IN_PARAM_4VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_5-VARCHAR2-IN")> ByVal IN_PARAM_5VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_6-VARCHAR2-IN")> ByVal IN_PARAM_6VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_7-VARCHAR2-IN")> ByVal IN_PARAM_7VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_8-VARCHAR2-IN")> ByVal IN_PARAM_8VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PARAM_9-VARCHAR2-IN")> ByVal IN_PARAM_9VARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_PASSWORD-VARCHAR2-IN")> ByVal IN_PASSWORDVARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("IN_SERVICEID-NUMBER-IN")> ByVal IN_SERVICEIDNUMBERIN As Double, <System.Xml.Serialization.XmlElementAttribute("IN_USERNAME-VARCHAR2-IN")> ByVal IN_USERNAMEVARCHAR2IN As String) As <System.Xml.Serialization.XmlElementAttribute("RETURN")> String
            Dim results() As Object = Me.Invoke("RMTO_WEB_SERVICES", New Object() {IN_PARAM_1VARCHAR2IN, IN_PARAM_10VARCHAR2IN, IN_PARAM_2VARCHAR2IN, IN_PARAM_3VARCHAR2IN, IN_PARAM_4VARCHAR2IN, IN_PARAM_5VARCHAR2IN, IN_PARAM_6VARCHAR2IN, IN_PARAM_7VARCHAR2IN, IN_PARAM_8VARCHAR2IN, IN_PARAM_9VARCHAR2IN, IN_PASSWORDVARCHAR2IN, IN_SERVICEIDNUMBERIN, IN_USERNAMEVARCHAR2IN})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RMTO_WEB_SERVICESAsync(ByVal IN_PARAM_1VARCHAR2IN As String, ByVal IN_PARAM_10VARCHAR2IN As String, ByVal IN_PARAM_2VARCHAR2IN As String, ByVal IN_PARAM_3VARCHAR2IN As String, ByVal IN_PARAM_4VARCHAR2IN As String, ByVal IN_PARAM_5VARCHAR2IN As String, ByVal IN_PARAM_6VARCHAR2IN As String, ByVal IN_PARAM_7VARCHAR2IN As String, ByVal IN_PARAM_8VARCHAR2IN As String, ByVal IN_PARAM_9VARCHAR2IN As String, ByVal IN_PASSWORDVARCHAR2IN As String, ByVal IN_SERVICEIDNUMBERIN As Double, ByVal IN_USERNAMEVARCHAR2IN As String)
            Me.RMTO_WEB_SERVICESAsync(IN_PARAM_1VARCHAR2IN, IN_PARAM_10VARCHAR2IN, IN_PARAM_2VARCHAR2IN, IN_PARAM_3VARCHAR2IN, IN_PARAM_4VARCHAR2IN, IN_PARAM_5VARCHAR2IN, IN_PARAM_6VARCHAR2IN, IN_PARAM_7VARCHAR2IN, IN_PARAM_8VARCHAR2IN, IN_PARAM_9VARCHAR2IN, IN_PASSWORDVARCHAR2IN, IN_SERVICEIDNUMBERIN, IN_USERNAMEVARCHAR2IN, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RMTO_WEB_SERVICESAsync(ByVal IN_PARAM_1VARCHAR2IN As String, ByVal IN_PARAM_10VARCHAR2IN As String, ByVal IN_PARAM_2VARCHAR2IN As String, ByVal IN_PARAM_3VARCHAR2IN As String, ByVal IN_PARAM_4VARCHAR2IN As String, ByVal IN_PARAM_5VARCHAR2IN As String, ByVal IN_PARAM_6VARCHAR2IN As String, ByVal IN_PARAM_7VARCHAR2IN As String, ByVal IN_PARAM_8VARCHAR2IN As String, ByVal IN_PARAM_9VARCHAR2IN As String, ByVal IN_PASSWORDVARCHAR2IN As String, ByVal IN_SERVICEIDNUMBERIN As Double, ByVal IN_USERNAMEVARCHAR2IN As String, ByVal userState As Object)
            If (Me.RMTO_WEB_SERVICESOperationCompleted Is Nothing) Then
                Me.RMTO_WEB_SERVICESOperationCompleted = AddressOf Me.OnRMTO_WEB_SERVICESOperationCompleted
            End If
            Me.InvokeAsync("RMTO_WEB_SERVICES", New Object() {IN_PARAM_1VARCHAR2IN, IN_PARAM_10VARCHAR2IN, IN_PARAM_2VARCHAR2IN, IN_PARAM_3VARCHAR2IN, IN_PARAM_4VARCHAR2IN, IN_PARAM_5VARCHAR2IN, IN_PARAM_6VARCHAR2IN, IN_PARAM_7VARCHAR2IN, IN_PARAM_8VARCHAR2IN, IN_PARAM_9VARCHAR2IN, IN_PASSWORDVARCHAR2IN, IN_SERVICEIDNUMBERIN, IN_USERNAMEVARCHAR2IN}, Me.RMTO_WEB_SERVICESOperationCompleted, userState)
        End Sub
        
        Private Sub OnRMTO_WEB_SERVICESOperationCompleted(ByVal arg As Object)
            If (Not (Me.RMTO_WEB_SERVICESCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RMTO_WEB_SERVICESCompleted(Me, New RMTO_WEB_SERVICESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub RMTO_WEB_SERVICESCompletedEventHandler(ByVal sender As Object, ByVal e As RMTO_WEB_SERVICESCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RMTO_WEB_SERVICESCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
