'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PayanehWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PayanehWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PayanehWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private WebMethodLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodGetTruckDriverByNationalCodefromRMTOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebMethodGetTruckBySmartCarNofromRMTOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PayanehClassLibrary.My.MySettings.Default.PayanehClassLibrary_PayanehWS_PayanehWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event WebMethodLoginCompleted As WebMethodLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodGetTruckDriverByNationalCodefromRMTOCompleted As WebMethodGetTruckDriverByNationalCodefromRMTOCompletedEventHandler
        
        '''<remarks/>
        Public Event WebMethodGetTruckBySmartCarNofromRMTOCompleted As WebMethodGetTruckBySmartCarNofromRMTOCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodLogin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodLogin(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String) As Long
            Dim results() As Object = Me.Invoke("WebMethodLogin", New Object() {YourUserShenaseh, YourUserPassword})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodLoginAsync(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String)
            Me.WebMethodLoginAsync(YourUserShenaseh, YourUserPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodLoginAsync(ByVal YourUserShenaseh As String, ByVal YourUserPassword As String, ByVal userState As Object)
            If (Me.WebMethodLoginOperationCompleted Is Nothing) Then
                Me.WebMethodLoginOperationCompleted = AddressOf Me.OnWebMethodLoginOperationCompleted
            End If
            Me.InvokeAsync("WebMethodLogin", New Object() {YourUserShenaseh, YourUserPassword}, Me.WebMethodLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodLoginCompleted(Me, New WebMethodLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodGetTruckDriverByNationalCodefromRMTO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodGetTruckDriverByNationalCodefromRMTO(ByVal YourNationalCode As String, ByVal YourExchangeKey As Long) As R2CoreTransportationAndLoadNotificationTruckDriver
            Dim results() As Object = Me.Invoke("WebMethodGetTruckDriverByNationalCodefromRMTO", New Object() {YourNationalCode, YourExchangeKey})
            Return CType(results(0),R2CoreTransportationAndLoadNotificationTruckDriver)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetTruckDriverByNationalCodefromRMTOAsync(ByVal YourNationalCode As String, ByVal YourExchangeKey As Long)
            Me.WebMethodGetTruckDriverByNationalCodefromRMTOAsync(YourNationalCode, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetTruckDriverByNationalCodefromRMTOAsync(ByVal YourNationalCode As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodGetTruckDriverByNationalCodefromRMTOOperationCompleted Is Nothing) Then
                Me.WebMethodGetTruckDriverByNationalCodefromRMTOOperationCompleted = AddressOf Me.OnWebMethodGetTruckDriverByNationalCodefromRMTOOperationCompleted
            End If
            Me.InvokeAsync("WebMethodGetTruckDriverByNationalCodefromRMTO", New Object() {YourNationalCode, YourExchangeKey}, Me.WebMethodGetTruckDriverByNationalCodefromRMTOOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodGetTruckDriverByNationalCodefromRMTOOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodGetTruckDriverByNationalCodefromRMTOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodGetTruckDriverByNationalCodefromRMTOCompleted(Me, New WebMethodGetTruckDriverByNationalCodefromRMTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebMethodGetTruckBySmartCarNofromRMTO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebMethodGetTruckBySmartCarNofromRMTO(ByVal YourSmartCardNo As String, ByVal YourExchangeKey As Long) As R2CoreTransportationAndLoadNotificationTruck
            Dim results() As Object = Me.Invoke("WebMethodGetTruckBySmartCarNofromRMTO", New Object() {YourSmartCardNo, YourExchangeKey})
            Return CType(results(0),R2CoreTransportationAndLoadNotificationTruck)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetTruckBySmartCarNofromRMTOAsync(ByVal YourSmartCardNo As String, ByVal YourExchangeKey As Long)
            Me.WebMethodGetTruckBySmartCarNofromRMTOAsync(YourSmartCardNo, YourExchangeKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebMethodGetTruckBySmartCarNofromRMTOAsync(ByVal YourSmartCardNo As String, ByVal YourExchangeKey As Long, ByVal userState As Object)
            If (Me.WebMethodGetTruckBySmartCarNofromRMTOOperationCompleted Is Nothing) Then
                Me.WebMethodGetTruckBySmartCarNofromRMTOOperationCompleted = AddressOf Me.OnWebMethodGetTruckBySmartCarNofromRMTOOperationCompleted
            End If
            Me.InvokeAsync("WebMethodGetTruckBySmartCarNofromRMTO", New Object() {YourSmartCardNo, YourExchangeKey}, Me.WebMethodGetTruckBySmartCarNofromRMTOOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebMethodGetTruckBySmartCarNofromRMTOOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebMethodGetTruckBySmartCarNofromRMTOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebMethodGetTruckBySmartCarNofromRMTOCompleted(Me, New WebMethodGetTruckBySmartCarNofromRMTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class R2CoreTransportationAndLoadNotificationTruckDriver
        
        Private driverIdField As Long
        
        Private nameFamilyField As String
        
        Private nationalCodeField As String
        
        Private mobileNumberField As String
        
        Private fatherNameField As String
        
        Private drivingLicenseNoField As String
        
        Private addressField As String
        
        Private smartCardNoField As String
        
        '''<remarks/>
        Public Property DriverId() As Long
            Get
                Return Me.driverIdField
            End Get
            Set
                Me.driverIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameFamily() As String
            Get
                Return Me.nameFamilyField
            End Get
            Set
                Me.nameFamilyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NationalCode() As String
            Get
                Return Me.nationalCodeField
            End Get
            Set
                Me.nationalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MobileNumber() As String
            Get
                Return Me.mobileNumberField
            End Get
            Set
                Me.mobileNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FatherName() As String
            Get
                Return Me.fatherNameField
            End Get
            Set
                Me.fatherNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DrivingLicenseNo() As String
            Get
                Return Me.drivingLicenseNoField
            End Get
            Set
                Me.drivingLicenseNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SmartCardNo() As String
            Get
                Return Me.smartCardNoField
            End Get
            Set
                Me.smartCardNoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class R2CoreTransportationAndLoadNotificationTruck
        
        Private truckIdField As Long
        
        Private loaderTypeIdField As Long
        
        Private pelakField As String
        
        Private serialField As String
        
        Private smartCardNoField As String
        
        '''<remarks/>
        Public Property TruckId() As Long
            Get
                Return Me.truckIdField
            End Get
            Set
                Me.truckIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LoaderTypeId() As Long
            Get
                Return Me.loaderTypeIdField
            End Get
            Set
                Me.loaderTypeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pelak() As String
            Get
                Return Me.pelakField
            End Get
            Set
                Me.pelakField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Serial() As String
            Get
                Return Me.serialField
            End Get
            Set
                Me.serialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SmartCardNo() As String
            Get
                Return Me.smartCardNoField
            End Get
            Set
                Me.smartCardNoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodLoginCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodGetTruckDriverByNationalCodefromRMTOCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodGetTruckDriverByNationalCodefromRMTOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodGetTruckDriverByNationalCodefromRMTOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R2CoreTransportationAndLoadNotificationTruckDriver
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R2CoreTransportationAndLoadNotificationTruckDriver)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebMethodGetTruckBySmartCarNofromRMTOCompletedEventHandler(ByVal sender As Object, ByVal e As WebMethodGetTruckBySmartCarNofromRMTOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebMethodGetTruckBySmartCarNofromRMTOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R2CoreTransportationAndLoadNotificationTruck
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R2CoreTransportationAndLoadNotificationTruck)
            End Get
        End Property
    End Class
End Namespace
